server:
  port: 8082

spring:
  datasource:
    #type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/relations
    username: postgres
    password: "012345"
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
